### ISSUE TITLE
Ablate report inside/output values as unused when they are.

### ISSUE THREAD

**Issue by mmcgurn** [UBCHREST/ablate#335]
This input file reproduced the error:
```yaml
---
environment:
  title: _2dSlabBurner
  tagDirectory: false
arguments: {}
timestepper:
  name: theMainTimeStepper
  arguments:
    ts_type: rk
    ts_max_time: 1
    ts_max_steps: 1
    ts_dt: 1.0e-10
    ts_adapt_monitor: ""
    ts_adapt_safety: 0.8
  io:
    !ablate::io::Hdf5MultiFileSerializer
    interval: 1
  domain: !ablate::domain::BoxMeshBoundaryCells
    name: simpleBoxField
    faces: [160, 24]
    lower: [ -0.03, 0.0]
    upper: [ 0.165354, 0.027686]
    simplex: false
    options:
      dm_refine: 0 #this must be zero
      dm_partition_view: 1
    preModifiers:
      #        dm_label_view: interiorFlowRegion
      - !ablate::domain::modifiers::DistributeWithGhostCells
        ghostCellDepth: 3
    postModifiers:
      - !ablate::domain::modifiers::MergeLabels
        mergedRegion:
          name: allBoundaryWalls
        regions:
          - name: boundaryCellsTop
          - name: boundaryCellsBottom
      - !ablate::domain::modifiers::CreateLabel
        # define the slab burner
        region:
          name: slabBurner
        function: !ablate::mathFunctions::geom::Surface
          path: ../geom/slabBurner.v1.stp
        # define the turbGen
      - !ablate::domain::modifiers::CreateLabel
        region:
          name: turbGen
        function: !ablate::mathFunctions::geom::Box
          lower: [0.0185345, -0.03] #y is lower than x-axis deliberately
          upper: [0.0220345, 0.005715]
      - !ablate::domain::modifiers::SubtractLabel
        # cut the slabBurner and turbGen out of the flowRegion
        differenceRegion:
          name: flowRegion
        minuendRegion:
          name: interiorCells
        subtrahendRegions:
          - name: slabBurner
          - name: turbGen
      - !ablate::domain::modifiers::SubtractLabel
        # cut the slabBurner and turbGen out of the boundaryWalls
        differenceRegion:
          name: boundaryWalls
        minuendRegion:
          name: allBoundaryWalls
        subtrahendRegions:
          - name: slabBurner
          - name: turbGen
      - !ablate::domain::modifiers::TagLabelInterface
        # define the boundary between the slab burner and flow
        leftRegion:
          name: flowRegion
        rightRegion:
          name: slabBurner
        boundaryFaceRegion:
          name: slabBurnerBoundaryFaces
        rightBoundaryCellRegion:
          name: slabBurnerBoundaryCells
        # define the boundary between the turbGen and the flow
      - !ablate::domain::modifiers::TagLabelInterface
        leftRegion:
          name: flowRegion
        rightRegion:
          name: turbGen
        boundaryFaceRegion:
          name: turbGenBoundaryFaces
        rightBoundaryCellRegion:
          name: turbGenBoundaryCells
      - !ablate::domain::modifiers::SubtractLabel
        # remove the slabBurnerFace from the flowRegion
        differenceRegion:
          name: interiorFlowRegion
        minuendRegion:
          name: flowRegion
        subtrahendRegions:
          - name: slabBurnerBoundaryFaces
        incompleteLabel: true
        # remove the turbGen from the boundary faces
      - !ablate::domain::modifiers::SubtractLabel
        differenceRegion:
          name: domainBoundaryFaces
        minuendRegion:
          name: boundaryFaces
        subtrahendRegions:
          - name: turbGen
      - !ablate::domain::modifiers::GhostBoundaryCells
    fields:
      - !ablate::finiteVolume::CompressibleFlowFields
        eos: !ablate::eos::TChem  &eos
          mechFile: ../mechanisms/grimech30.mech.dat
          thermoFile: ../mechanisms/grimech30.thermo.dat
        conservedFieldOptions:
          petscfv_type: upwind
        region:
          name: domain
      - !ablate::domain::FieldDescription
        name: pressure
        type: FV
        location: aux
        region:
          name: domain
  initialization:
    - !ablate::finiteVolume::fieldFunctions::Euler
      state: &flowFieldState
        eos: *eos
        temperature: !ablate::mathFunctions::geom::Sphere
          center: [.036,  0.01]
          radius: 0.005
          insideValues: [1500]
          outsideValues: [298.15]
        pressure: 101325.0
        velocity: "0, 0"
        massFractions: !ablate::finiteVolume::fieldFunctions::MassFractions
          &oxMassFrac
          eos: *eos
          values:
            - fieldName: O2
              field: 0.22968530497578818
            - fieldName: N2
              field: 0.7703146950242119
    - !ablate::finiteVolume::fieldFunctions::DensityMassFractions
      state: *flowFieldState
    - !ablate::finiteVolume::fieldFunctions::Euler
      region:
        name: turbGenBoundaryCells
      state: &turbGenState
        eos: *eos
        temperature: 653.0
        pressure: 101325.0
        velocity: "0.0, 0.0"
        massFractions: *oxMassFrac
    - !ablate::finiteVolume::fieldFunctions::DensityMassFractions
      region:
        name: turbGenBoundaryCells
      state: *turbGenState
    - !ablate::finiteVolume::fieldFunctions::Euler
      # slab Burner
      region:
        name: slabBurnerBoundaryCells
      state: &fuelFieldState
        eos: *eos
        temperature: 653.0
        pressure: 101325
        velocity: "0.0, 0.0"
        massFractions: !ablate::finiteVolume::fieldFunctions::MassFractions
          &fuelMassFrac
          eos: *eos
          values:
            - fieldName: H2
              field: 3.11573908295E-07
            - fieldName: CH4
              field: 1.37640311576E-01
            - fieldName: CO
              field: 5.59511130432E-01
            - fieldName: CO2
              field: 2.67621505110E-05
            - fieldName: C2H2
              field: 8.12221908950E-04
            - fieldName: C2H4
              field: 8.12221908950E-04
            - fieldName: C2H6
              field: 2.61085823724E-02
            - fieldName: CH2CO
              field: 2.00544314596E-07
            - fieldName: C3H8
              field: 2.51803728765E-02
    - !ablate::finiteVolume::fieldFunctions::DensityMassFractions
      region:
        name: slabBurnerBoundaryCells
      state: *fuelFieldState

solvers:
  - !ablate::finiteVolume::CompressibleFlowSolver
    id: flowField
    region:
      name: interiorFlowRegion
    parameters:
      cfl: 0.5
    eos: *eos
    transport: !ablate::eos::transport::Sutherland
      &transportModel
      eos: *eos
    additionalProcesses:
      - !ablate::finiteVolume::processes::PressureGradientScaling
        &pgs
        eos: *eos
        alphaInit: 25.0
        maxAlphaAllowed: 100.0
        domainLength: 0.165354
        log: !ablate::monitors::logs::StdOut
      - !ablate::finiteVolume::processes::TChemReactions
        eos: *eos
    fluxCalculator: !ablate::finiteVolume::fluxCalculator::AusmpUp
      pgs: *pgs
    monitors:
      - !ablate::monitors::TimeStepMonitor
        interval: 25
      - !ablate::monitors::PhysicsTimeStep
        interval: 25
      - !ablate::monitors::TurbFlowStats
        fields:
          - temperature
          - velocity
        eos: *eos
  - !ablate::boundarySolver::BoundarySolver
    id: inlet
    region:
      name: boundaryCellsLeft
    fieldBoundary:
      name: domainBoundaryFaces
    mergeFaces: true
    processes:
      - !ablate::boundarySolver::lodi::Inlet
        eos: *eos
        pgs: *pgs
        velocity: "min(15, t*15/.025) , 0.0"
  - !ablate::boundarySolver::BoundarySolver
    id: outlet
    region:
      name: boundaryCellsRight
    fieldBoundary:
      name: domainBoundaryFaces
    mergeFaces: true
    processes:
      - !ablate::boundarySolver::lodi::OpenBoundary
        eos: *eos
        referencePressure: 101325.0
        maxAcousticsLength: 0.165354
        reflectFactor: .15
        pgs: *pgs
  - !ablate::boundarySolver::BoundarySolver
    id: walls
    region:
      name: boundaryWalls
    fieldBoundary:
      name: domainBoundaryFaces
    mergeFaces: true
    processes:
      - !ablate::boundarySolver::lodi::IsothermalWall
        eos: *eos
        pgs: *pgs
  - !ablate::boundarySolver::BoundarySolver
    id: turbWalls
    region:
      name: turbGenBoundaryCells
    fieldBoundary:
      name: turbGenBoundaryFaces
    mergeFaces: true
    processes:
      - !ablate::boundarySolver::lodi::IsothermalWall
        eos: *eos
        pgs: *pgs
  - !ablate::boundarySolver::BoundarySolver
    id: slab boundary
    region:
      name: slabBurnerBoundaryCells
    fieldBoundary:
      name: slabBurnerBoundaryFaces
    processes:
      - !ablate::boundarySolver::physics::Sublimation
        latentHeatOfFusion: 941000.000
        transportModel: *transportModel
        pgs: *pgs
        eos: *eos
        additionalHeatFlux: !ablate::mathFunctions::geom::Sphere
          center: [.036,  0.01]
          radius: 0.005
          insideValues: "t < .03? 250000 : 0.0 "# 150 KW/m2
        massFractions: *fuelMassFrac
```
